---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true
  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 512
    cpus: 1

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: server
    run_list:
      - recipe[apt::default]
      - recipe[logstash::server]
    attributes:
      java:
        jdk_version: 7
        oracle: 
          accept_oracle_download_terms: true
        install_flavor: oracle
      logstash:
        server:
          enable_embedded_es: true
          web:
            enabled: true

