---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 13.1
  customize:
    memory: 512
    cpus: 1

provisioner:
  name: chef_zero
  attributes:
    java:
      jdk_version: "8"
      install_flavor: "oracle"
      oracle:
        accept_oracle_download_terms: true
    logstash:
      instance:
        server:
          elasticsearch_ip: '127.0.0.1'
          config_templates_variables:
            bind_host: '127.0.0.1'
            es_protocol: 'http'
          init_method: 'native'
          xms: '256M'
          xmx: '256M'
          logrotate_use_filesize: true
          logrotate_max_size: '25MB'
          config_templates:
            input_syslog: 'config/input_syslog.conf.erb'
            output_stdout: 'config/output_stdout.conf.erb'
            output_elasticsearch: 'config/output_elasticsearch.conf.erb'
          pattern_templates:
            default: 'patterns/custom_patterns.erb'

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
  - name: centos-6.9
    run_list:
      - recipe[java::default]
  - name: centos-7.3
    run_list:
      - recipe[java::default]

suites:
  - name: server
    run_list:
      - recipe[logstash-test::default]
