AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'test/support/**'
    - 'bin/**/*'
    - 'test/**'
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Vagrantfile'
    - '**/Berksfile'

Style/FrozenStringLiteralComment:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

LineLength:
  Enabled: true
  Max: 210

MethodLength:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

AccessorMethodName:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

UselessAssignment:
  Enabled: false

BlockNesting:
  Max: 4

Documentation:
  Enabled: false

MethodLength:
  Max: 50

Style/WordArray:
  MinSize: 5

Style/RedundantBegin:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 9
Metrics/AbcSize:
  Max: 78

# Offense count: 8
Metrics/PerceivedComplexity:
  Max: 25

Metrics/AbcSize:
  Max: 90

Style/NestedModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfUnlessModifierOfIfUnless:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false
