AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'test/support/**'
    - 'bin/**/*'
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
CyclomaticComplexity:
  Enabled: false

LineLength:
  Enabled: true
  Max: 200

MethodLength:
  Enabled: true
  Max: 20

AccessorMethodName:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

UselessAssignment:
  Enabled: false

BlockNesting:
  Max: 4

Documentation:
  Enabled: false

MethodLength:
  Max: 50

SingleSpaceBeforeFirstArg:
  Enabled: false

Style/WordArray:
  MinSize: 5

Style/RedundantBegin:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 9
Metrics/AbcSize:
  Max: 78

# Offense count: 8
Metrics/PerceivedComplexity:
  Max: 18
