metadata
cookbook 'apt'
cookbook 'logrotate'
cookbook 'vim'
cookbook 'monit'
cookbook 'nginx'
cookbook 'yum'
cookbook 'java'
cookbook 'rabbitmq', git: 'git://github.com/opscode-cookbooks/rabbitmq.git'
cookbook 'minitest-handler', git: 'git://github.com/btm/minitest-handler-cookbook.git'
cookbook 'elasticsearch', git: 'git://github.com/bryanwb/cookbook-elasticsearch.git'
