metadata
cookbook 'logrotate'
cookbook 'yum'
cookbook 'java'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'apache2'
cookbook 'rvm', git: 'git://github.com/fnichol/chef-rvm.git'
cookbook 'rabbitmq', git: 'git://github.com/opscode-cookbooks/rabbitmq.git'
cookbook 'minitest-handler', git: 'git://github.com/btm/minitest-handler-cookbook.git'
cookbook 'elasticsearch', git: 'git://github.com/elasticsearch/cookbook-elasticsearch.git'
