metadata
cookbook 'logrotate'
cookbook 'yum'
cookbook 'java'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'apache2'
cookbook 'ark'
cookbook 'yumrepo', git: 'https://github.com/bryanwb/cookbook-yumrepo.git'
cookbook 'rbenv', git: 'https://github.com/RiotGames/rbenv-cookbook.git'
cookbook 'ruby_build', git: 'https://github.com/fnichol/chef-ruby_build.git'
cookbook 'rabbitmq', git: 'https://github.com/opscode-cookbooks/rabbitmq.git'
cookbook 'minitest-handler', git: 'https://github.com/btm/minitest-handler-cookbook.git'
cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch.git'