source "https://rubygems.org"

gem 'rake'
gem 'foodcritic', :platforms => :ruby_19
gem 'chef', :platforms => :ruby_19
gem 'berkshelf', :platforms => :ruby_19
gem 'rubocop', '~> 0.16.0', :platforms => :ruby_19
gem 'chefspec', :platforms => :ruby_19
gem 'strainer', :platforms => :ruby_19
