###
# This is the place to override the logstash cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "logstash/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Logstash debug and enable_embedded_es settings:
#
#normal[:logstash][:server][:debug] = true
#normal[:logstash][:server][:enable_embedded_es] = false
